export const JOB_TARGETS = [
  {
    type: 'react',
    mustHave: ['react', 'reactjs', 'react.js', 'next.js', 'nextjs', 'react js'],
    keywords: [
      'react',
      'react.js',
      'reactjs',
      'nextjs',
      'next.js',
      'typescript',
      'redux',
      'tailwind',
      'frontend',
      'vite',
      'zustand',
      'react query',
      'shadcn',
      'context api',
    ],
    url: 'https://www.naukri.com/react-dot-js-react-js-developer-react-js-frontend-developer-react-developer-nextjs-typescript-javascript-jobs?k=react.js%2C%20react%20js%20developer%2C%20react%20js%20frontend%20developer%2C%20react%20developer%2C%20nextjs%2C%20typescript%2C%20javascript&experience=3&nignbevent_src=jobsearchDeskGNB',
  },
  {
    type: 'mern',
    mustHave: ['mern', 'mern stack', 'node.js', 'nodejs', 'node js'],
    keywords: [
      'mern',
      'mern stack',
      'mongodb',
      'express',
      'expressjs',
      'react',
      'node.js',
      'nodejs',
      'nestjs',
      'backend',
      'rest api',
      'graphql',
      'mongoose',
      'full stack',
    ],
    url: 'https://www.naukri.com/mern-stack-mern-stack-developer-mern-full-stack-developer-frontend-development-frontend-software-developer-node-dot-js-backend-mern-stack-mern-express-nestjs-jobs?k=mern%20stack%2C%20mern%20stack%20developer%2C%20mern%20full%20stack%20developer%2C%20frontend%20development%2C%20frontend%20software%20developer%2C%20node.js%2C%20backend%2C%20mern%20stack%2C%20mern%2C%20express%2C%20nestjs&experience=3&nignbevent_src=jobsearchDeskGNB',
  },
  {
    type: 'reactnative-node',
    mustHave: ['react native', 'reactnative', 'react-native'],
    keywords: [
      'react native',
      'reactnative',
      'expo',
      'ios',
      'android',
      'mobile',
      'node.js',
      'nodejs',
      'backend',
      'express',
      'nestjs',
      'redux',
      'navigation',
    ],
    url: 'https://www.naukri.com/react-native-react-native-developer-react-native-mobile-application-developer-node-dot-js-node-js-backend-developer-node-js-developer-backend-development-backend-react-native-jobs?k=react%20native%2C%20react%20native%20developer%2C%20react%20native%20mobile%20application%20developer%2C%20node.js%2C%20node%20js%20backend%20developer%2C%20node%20js%20developer%2C%20backend%20development%2C%20backend%2C%20react%20native&experience=3&nignbevent_src=jobsearchDeskGNB',
  },
];
